export type IncentiveSection = "A" | "B" | "C";

export type IncentiveItem = {
  code: string;
  section: IncentiveSection;
  category: string;
  title: string;
  department: string;
  amountLabel: string;
  amountKes: number | null;
  frequency: string;
  trigger: string;
  eligibility: string;
  guardrails: string;
};

export const DEPARTMENTS = [
  "Sales",
  "Tax",
  "Bookkeeping",
  "Payroll",
  "Consultation",
  "Fulfillment",
  "Management",
] as const;

export const SUBMISSION_STATUSES = [
  "Submitted",
  "Under review",
  "Approved",
  "Needs info",
  "Paid",
  "Declined",
] as const;

export const INCENTIVE_CATALOG: IncentiveItem[] = [
  {
    code: "A1.1",
    section: "A",
    category: "Client acquisition",
    title: "Subscription client, independent",
    department: "Sales",
    amountLabel: "KES 3,500",
    amountKes: 3500,
    frequency: "One-time",
    trigger: "New bookkeeping or payroll subscription client is acquired independently.",
    eligibility: "Employee who acquired the client.",
    guardrails: "Use A1.2 when Consultation or Andrew materially supported the close.",
  },
  {
    code: "A1.2",
    section: "A",
    category: "Client acquisition",
    title: "Subscription client with Consultation or Andrew support",
    department: "Sales, Consultation",
    amountLabel: "KES 2,000 employee + KES 1,500 support",
    amountKes: 3500,
    frequency: "One-time",
    trigger: "New bookkeeping or payroll subscription client is acquired with support.",
    eligibility: "Acquiring employee and Consultation or Andrew support.",
    guardrails: "Split should be recorded on the same claim or cross-referenced claims.",
  },
  {
    code: "A1.3",
    section: "A",
    category: "Client acquisition",
    title: "Tax-only client, independent",
    department: "Sales, Tax",
    amountLabel: "KES 1,000",
    amountKes: 1000,
    frequency: "One-time",
    trigger: "New tax-only client is acquired independently.",
    eligibility: "Employee who acquired the client.",
    guardrails: "Stacks with A10 only when the client came through a converted referral.",
  },
  {
    code: "A1.4",
    section: "A",
    category: "Client acquisition",
    title: "Tax-only client with Andrew support",
    department: "Sales, Tax",
    amountLabel: "KES 500 employee + KES 500 support",
    amountKes: 1000,
    frequency: "One-time",
    trigger: "New tax-only client is acquired with Andrew support.",
    eligibility: "Acquiring employee and Andrew support.",
    guardrails: "Split should be recorded on the same claim or cross-referenced claims.",
  },
  {
    code: "A1.5",
    section: "A",
    category: "Client acquisition",
    title: "Sales team member, any client",
    department: "Sales",
    amountLabel: "KES 2,000 employee + KES 1,500 support",
    amountKes: 3500,
    frequency: "One-time",
    trigger: "Sales team member closes any eligible client.",
    eligibility: "Sales employee and Consultation or Andrew support where applicable.",
    guardrails: "Do not combine with another A1 acquisition scenario for the same client.",
  },
  {
    code: "A2",
    section: "A",
    category: "Sales milestone",
    title: "Permanent salary increase per 10 cumulative clients",
    department: "Sales",
    amountLabel: "KES 5,000 per month",
    amountKes: 5000,
    frequency: "Permanent monthly",
    trigger: "Every 10 cumulative clients acquired.",
    eligibility: "Sales employee reaching the cumulative-client milestone.",
    guardrails: "Uncapped; payroll should retain prior milestone increments.",
  },
  {
    code: "A3.1",
    section: "A",
    category: "Payroll onboarding",
    title: "Standard payroll onboarding",
    department: "Payroll",
    amountLabel: "KES 500",
    amountKes: 500,
    frequency: "One-time",
    trigger: "Payroll onboarding for 1 to 10 employees is completed.",
    eligibility: "Payroll employee who completed onboarding.",
    guardrails: "Use A3.2 for 11 or more employees or multi-state onboarding.",
  },
  {
    code: "A3.2",
    section: "A",
    category: "Payroll onboarding",
    title: "Complex payroll onboarding",
    department: "Payroll",
    amountLabel: "KES 1,000",
    amountKes: 1000,
    frequency: "One-time",
    trigger: "Payroll onboarding for 11 or more employees, or multi-state setup, is completed.",
    eligibility: "Payroll employee who completed onboarding.",
    guardrails: "Attach onboarding checklist, employee count, and state details where relevant.",
  },
  {
    code: "A4",
    section: "A",
    category: "Fulfillment group incentive",
    title: "Quarterly group acquisition-pool share",
    department: "Fulfillment",
    amountLabel: "10% of quarterly acquisition-bonus pool",
    amountKes: null,
    frequency: "Quarterly",
    trigger: "Each 10 new clients company-wide in the quarter.",
    eligibility: "Fulfillment group; team leader receives 1.5x share, staff and generalists receive 1x.",
    guardrails: "Pay only if quarterly error rate is below 5%.",
  },
  {
    code: "A5.1",
    section: "A",
    category: "Client retention",
    title: "Bookkeeping retention anniversary",
    department: "Bookkeeping",
    amountLabel: "KES 2,000",
    amountKes: 2000,
    frequency: "Annual",
    trigger: "Bookkeeping client reaches each 12-month anniversary.",
    eligibility: "Employee responsible for retained service relationship.",
    guardrails: "Use A5.3 when the client has both bookkeeping and payroll.",
  },
  {
    code: "A5.2",
    section: "A",
    category: "Client retention",
    title: "Payroll retention anniversary",
    department: "Payroll",
    amountLabel: "KES 1,500",
    amountKes: 1500,
    frequency: "Annual",
    trigger: "Payroll client reaches each 12-month anniversary.",
    eligibility: "Employee responsible for retained service relationship.",
    guardrails: "Use A5.3 when the client has both bookkeeping and payroll.",
  },
  {
    code: "A5.3",
    section: "A",
    category: "Client retention",
    title: "Bookkeeping and payroll retention anniversary",
    department: "Bookkeeping, Payroll",
    amountLabel: "KES 3,000",
    amountKes: 3000,
    frequency: "Annual",
    trigger: "Client with both services reaches each 12-month anniversary.",
    eligibility: "Employee responsible for retained service relationship.",
    guardrails: "Do not stack A5.1 and A5.2 for the same anniversary when A5.3 applies.",
  },
  {
    code: "A6.1",
    section: "A",
    category: "Bookkeeping performance",
    title: "Bookkeeping accuracy",
    department: "Bookkeeping",
    amountLabel: "KES 2,000",
    amountKes: 2000,
    frequency: "Quarterly",
    trigger: "Bookkeeping accuracy threshold is met for the quarter.",
    eligibility: "Bookkeeping employee.",
    guardrails: "Attach quality review or error report for the quarter.",
  },
  {
    code: "A6.2",
    section: "A",
    category: "Bookkeeping performance",
    title: "Bookkeeping turnaround",
    department: "Bookkeeping",
    amountLabel: "KES 1,500",
    amountKes: 1500,
    frequency: "Quarterly",
    trigger: "Bookkeeping turnaround threshold is met for the quarter.",
    eligibility: "Bookkeeping employee.",
    guardrails: "Attach work queue or service-level evidence.",
  },
  {
    code: "A6.3",
    section: "A",
    category: "Books cleanup",
    title: "Standard books cleanup",
    department: "Bookkeeping",
    amountLabel: "KES 1,000 per client",
    amountKes: 1000,
    frequency: "Per client",
    trigger: "Standard books cleanup is completed.",
    eligibility: "Bookkeeping employee who completed cleanup.",
    guardrails: "Attach completion notes or client-ready deliverable.",
  },
  {
    code: "A6.4",
    section: "A",
    category: "Books cleanup",
    title: "Complex books cleanup",
    department: "Bookkeeping",
    amountLabel: "KES 2,000 per client",
    amountKes: 2000,
    frequency: "Per client",
    trigger: "Complex books cleanup is completed.",
    eligibility: "Bookkeeping employee who completed cleanup.",
    guardrails: "Attach scope notes showing complexity.",
  },
  {
    code: "A7.1",
    section: "A",
    category: "Tax performance",
    title: "Tax accuracy",
    department: "Tax",
    amountLabel: "KES 3,000",
    amountKes: 3000,
    frequency: "Quarterly",
    trigger: "Tax accuracy threshold is met for the quarter.",
    eligibility: "Tax employee.",
    guardrails: "Attach quality review or error report for the quarter.",
  },
  {
    code: "A7.2",
    section: "A",
    category: "Tax performance",
    title: "Tax deadline adherence",
    department: "Tax",
    amountLabel: "KES 2,000",
    amountKes: 2000,
    frequency: "Quarterly",
    trigger: "Tax filing deadline threshold is met for the quarter.",
    eligibility: "Tax employee.",
    guardrails: "Attach filing tracker evidence.",
  },
  {
    code: "A7.3",
    section: "A",
    category: "Tax return complexity",
    title: "Complex return",
    department: "Tax",
    amountLabel: "KES 500 per return",
    amountKes: 500,
    frequency: "Per return",
    trigger: "Complex return is completed.",
    eligibility: "Tax employee who completed the return.",
    guardrails: "Attach return complexity notes.",
  },
  {
    code: "A7.4",
    section: "A",
    category: "Tax return complexity",
    title: "Highly complex return",
    department: "Tax",
    amountLabel: "KES 1,000 per return",
    amountKes: 1000,
    frequency: "Per return",
    trigger: "Highly complex return is completed.",
    eligibility: "Tax employee who completed the return.",
    guardrails: "Attach complexity approval or review notes.",
  },
  {
    code: "A7.5",
    section: "A",
    category: "Tax recognition",
    title: "Four quarters with zero errors and zero late filings",
    department: "Tax",
    amountLabel: "KES 10,000",
    amountKes: 10000,
    frequency: "One-time",
    trigger: "Zero errors and zero late filings across 4 consecutive quarters.",
    eligibility: "Tax employee.",
    guardrails: "Cross-check with B9 if your policy treats these as the same recognition bonus.",
  },
  {
    code: "A8.1",
    section: "A",
    category: "Payroll performance",
    title: "Payroll accuracy",
    department: "Payroll",
    amountLabel: "KES 2,000",
    amountKes: 2000,
    frequency: "Quarterly",
    trigger: "Payroll accuracy threshold is met for the quarter.",
    eligibility: "Payroll employee.",
    guardrails: "Attach payroll QA or error report.",
  },
  {
    code: "A8.2",
    section: "A",
    category: "Payroll performance",
    title: "Payroll deadline adherence",
    department: "Payroll",
    amountLabel: "KES 1,500",
    amountKes: 1500,
    frequency: "Quarterly",
    trigger: "Payroll deadline threshold is met for the quarter.",
    eligibility: "Payroll employee.",
    guardrails: "Attach payroll calendar or processing evidence.",
  },
  {
    code: "A8.3",
    section: "A",
    category: "Payroll recognition",
    title: "Full year with zero errors and zero missed deadlines",
    department: "Payroll",
    amountLabel: "KES 8,000",
    amountKes: 8000,
    frequency: "One-time",
    trigger: "Zero payroll errors and zero missed deadlines for a full year.",
    eligibility: "Payroll employee.",
    guardrails: "Cross-check with B10 if your policy treats these as the same recognition bonus.",
  },
  {
    code: "A9.1",
    section: "A",
    category: "Consultation performance",
    title: "Consultation response time",
    department: "Consultation",
    amountLabel: "KES 1,500",
    amountKes: 1500,
    frequency: "Quarterly",
    trigger: "Response-time threshold is met for the quarter.",
    eligibility: "Consultation or Research employee.",
    guardrails: "Attach response-time report.",
  },
  {
    code: "A9.2",
    section: "A",
    category: "Consultation performance",
    title: "Research quality",
    department: "Consultation",
    amountLabel: "KES 2,000",
    amountKes: 2000,
    frequency: "Quarterly",
    trigger: "Research quality threshold is met for the quarter.",
    eligibility: "Consultation or Research employee.",
    guardrails: "Attach reviewed research output or scorecard.",
  },
  {
    code: "A9.3",
    section: "A",
    category: "Consultation performance",
    title: "Client satisfaction",
    department: "Consultation",
    amountLabel: "KES 1,500",
    amountKes: 1500,
    frequency: "Quarterly",
    trigger: "Client satisfaction threshold is met for the quarter.",
    eligibility: "Consultation or Research employee.",
    guardrails: "Attach client satisfaction report.",
  },
  {
    code: "A9.4",
    section: "A",
    category: "Consultation revenue split",
    title: "Sales-acquired client revenue split",
    department: "Consultation",
    amountLabel: "KES 1,500 per client",
    amountKes: 1500,
    frequency: "Per client",
    trigger: "Sales-acquired client creates Consultation revenue split eligibility.",
    eligibility: "Consultation or Research employee.",
    guardrails: "Cross-reference the Sales acquisition claim.",
  },
  {
    code: "A10",
    section: "A",
    category: "Referral",
    title: "Cross-department converted referral",
    department: "Company-wide",
    amountLabel: "KES 1,500",
    amountKes: 1500,
    frequency: "Per converted referral",
    trigger: "Cross-department referral converts to a client.",
    eligibility: "Employee who made the converted referral.",
    guardrails: "Stackable with acquisition bonus when both apply.",
  },
  {
    code: "A11",
    section: "A",
    category: "Team building",
    title: "Post-tax-season group reward",
    department: "Company-wide",
    amountLabel: "Management discretion",
    amountKes: null,
    frequency: "Post tax season",
    trigger: "Management approves group reward based on company performance.",
    eligibility: "Eligible group determined by management.",
    guardrails: "Record management approval and performance basis.",
  },
  {
    code: "B1",
    section: "B",
    category: "Quarterly salary increment",
    title: "Sales quarterly permanent salary increment",
    department: "Sales",
    amountLabel: "KES 3,000 / 5,000 / 8,000 per month",
    amountKes: null,
    frequency: "Quarterly permanent monthly",
    trigger: "Sales employee meets, exceeds, or reaches outstanding quarterly threshold.",
    eligibility: "Sales employee.",
    guardrails: "Maximum annual increase: KES 32,000 per month.",
  },
  {
    code: "B2",
    section: "B",
    category: "Quarterly salary increment",
    title: "Tax quarterly permanent salary increment",
    department: "Tax",
    amountLabel: "KES 3,000 / 5,000 / 7,000 per month",
    amountKes: null,
    frequency: "Quarterly permanent monthly",
    trigger: "Tax employee meets, exceeds, or reaches outstanding quarterly threshold.",
    eligibility: "Tax employee.",
    guardrails: "Maximum annual increase: KES 28,000 per month.",
  },
  {
    code: "B3",
    section: "B",
    category: "Quarterly salary increment",
    title: "Bookkeeping quarterly permanent salary increment",
    department: "Bookkeeping",
    amountLabel: "KES 2,500 / 4,000 / 6,000 per month",
    amountKes: null,
    frequency: "Quarterly permanent monthly",
    trigger: "Bookkeeping employee meets, exceeds, or reaches outstanding quarterly threshold.",
    eligibility: "Bookkeeping employee.",
    guardrails: "Maximum annual increase: KES 24,000 per month.",
  },
  {
    code: "B4",
    section: "B",
    category: "Quarterly salary increment",
    title: "Payroll quarterly permanent salary increment",
    department: "Payroll",
    amountLabel: "KES 2,500 / 4,000 / 6,000 per month",
    amountKes: null,
    frequency: "Quarterly permanent monthly",
    trigger: "Payroll employee meets, exceeds, or reaches outstanding quarterly threshold.",
    eligibility: "Payroll employee.",
    guardrails: "Maximum annual increase: KES 24,000 per month.",
  },
  {
    code: "B5",
    section: "B",
    category: "Quarterly salary increment",
    title: "Consultation quarterly permanent salary increment",
    department: "Consultation",
    amountLabel: "KES 3,000 / 5,000 / 7,500 per month",
    amountKes: null,
    frequency: "Quarterly permanent monthly",
    trigger: "Consultation employee meets, exceeds, or reaches outstanding quarterly threshold.",
    eligibility: "Consultation employee.",
    guardrails: "Maximum annual increase: KES 30,000 per month.",
  },
  {
    code: "B7.1",
    section: "B",
    category: "Team leader quarterly payment",
    title: "Team and personal thresholds both met",
    department: "Company-wide",
    amountLabel: "KES 2,500",
    amountKes: 2500,
    frequency: "Quarterly one-time",
    trigger: "Team leader personal and team thresholds are both met.",
    eligibility: "Team leader.",
    guardrails: "Attach personal and team scorecards.",
  },
  {
    code: "B7.2",
    section: "B",
    category: "Team leader quarterly payment",
    title: "Team threshold met, personal threshold not met",
    department: "Company-wide",
    amountLabel: "KES 1,500",
    amountKes: 1500,
    frequency: "Quarterly one-time",
    trigger: "Team threshold is met but team leader personal threshold is not met.",
    eligibility: "Team leader.",
    guardrails: "Attach team scorecard and personal result.",
  },
  {
    code: "B8",
    section: "B",
    category: "Consecutive performance recognition",
    title: "Sales outstanding in 2 consecutive quarters",
    department: "Sales",
    amountLabel: "KES 5,000",
    amountKes: 5000,
    frequency: "One-time",
    trigger: "Outstanding rating in 2 consecutive quarters.",
    eligibility: "Sales employee.",
    guardrails: "Attach the two quarterly scorecards.",
  },
  {
    code: "B9",
    section: "B",
    category: "Consecutive performance recognition",
    title: "Tax 4 consecutive qualifying quarters",
    department: "Tax",
    amountLabel: "KES 10,000",
    amountKes: 10000,
    frequency: "One-time",
    trigger: "4 consecutive qualifying quarters.",
    eligibility: "Tax employee.",
    guardrails: "Cross-check with A7.5 if your policy treats these as the same recognition bonus.",
  },
  {
    code: "B10",
    section: "B",
    category: "Consecutive performance recognition",
    title: "Payroll full-year zero-error recognition",
    department: "Payroll",
    amountLabel: "KES 8,000",
    amountKes: 8000,
    frequency: "One-time",
    trigger: "Full year of zero errors and zero missed deadlines.",
    eligibility: "Payroll employee.",
    guardrails: "Cross-check with A8.3 if your policy treats these as the same recognition bonus.",
  },
  {
    code: "C1.1",
    section: "C",
    category: "EA examination salary increment",
    title: "EA Level 1 - Individuals",
    department: "Tax, Consultation",
    amountLabel: "KES 5,000 per month",
    amountKes: 5000,
    frequency: "Permanent monthly",
    trigger: "EA Level 1 is passed and 5 advisory clients are active.",
    eligibility: "Employee with EA Level 1 and advisory client threshold.",
    guardrails: "Attach exam pass evidence and advisory client list.",
  },
  {
    code: "C1.2",
    section: "C",
    category: "EA examination salary increment",
    title: "EA Level 2 - Businesses",
    department: "Tax, Consultation",
    amountLabel: "KES 10,000 per month",
    amountKes: 10000,
    frequency: "Permanent monthly",
    trigger: "EA Level 2 is passed and 10 advisory clients are active.",
    eligibility: "Employee with EA Level 2 and advisory client threshold.",
    guardrails: "Attach exam pass evidence and advisory client list.",
  },
  {
    code: "C1.3",
    section: "C",
    category: "EA examination salary increment",
    title: "EA Level 3 - Representation",
    department: "Tax, Consultation",
    amountLabel: "KES 15,000 per month",
    amountKes: 15000,
    frequency: "Permanent monthly",
    trigger: "EA Level 3 is passed and 15 advisory clients are active.",
    eligibility: "Employee with EA Level 3 and advisory client threshold.",
    guardrails: "Attach exam pass evidence and advisory client list.",
  },
  {
    code: "C1.4",
    section: "C",
    category: "EA examination salary increment",
    title: "Full EA completion",
    department: "Tax, Consultation",
    amountLabel: "KES 30,000 per month total",
    amountKes: 30000,
    frequency: "Permanent monthly",
    trigger: "All three EA levels are passed.",
    eligibility: "Employee with full EA completion.",
    guardrails: "Record as total EA salary increment, not in addition to all individual level rows unless policy says otherwise.",
  },
  {
    code: "C2.1",
    section: "C",
    category: "EA mentorship",
    title: "EA Level 1 mentorship",
    department: "Tax, Consultation",
    amountLabel: "KES 3,000",
    amountKes: 3000,
    frequency: "One-time",
    trigger: "Mentee passes EA Level 1.",
    eligibility: "Mentor who supported the passing mentee.",
    guardrails: "Attach mentee pass confirmation and mentor assignment.",
  },
  {
    code: "C2.2",
    section: "C",
    category: "EA mentorship",
    title: "EA Level 2 mentorship",
    department: "Tax, Consultation",
    amountLabel: "KES 4,000",
    amountKes: 4000,
    frequency: "One-time",
    trigger: "Mentee passes EA Level 2.",
    eligibility: "Mentor who supported the passing mentee.",
    guardrails: "Attach mentee pass confirmation and mentor assignment.",
  },
  {
    code: "C2.3",
    section: "C",
    category: "EA mentorship",
    title: "EA Level 3 mentorship",
    department: "Tax, Consultation",
    amountLabel: "KES 5,000",
    amountKes: 5000,
    frequency: "One-time",
    trigger: "Mentee passes EA Level 3.",
    eligibility: "Mentor who supported the passing mentee.",
    guardrails: "Attach mentee pass confirmation and mentor assignment.",
  },
];

export function getIncentive(code: string) {
  return INCENTIVE_CATALOG.find((item) => item.code === code);
}
